### ISSUE TITLE
Issue with end users running verify

### ISSUE THREAD

**Issue by mabaugh83** [pnp/provision-assist-m365#1]
### Description

When creating a request as a user with full control over sharepoint site, the verify works fine. When doing as a visitor with read access on request list, clicking verify does nothing and in errors 
CheckSpaceAvailability.Run failed: Connection not configured for this service.

have validated that flows are shared with end user

Additionally in teams, the template screen only shows the description and no image

### Steps to reproduce

1.create a new request
2.Use any type
3. enter name
4. click verify

### Expected results

on clicking verify would get response

### Actual Results

nothing but error CheckSpaceAvailability.Run failed: Connection not configured for this service.

### Solution component

Power App

### Operating system (environment)

Windows

**Comment by alexc-MSFT** [comment]
@mabaugh83 thanks for raising this issue. For the 'Connection not configured for this service' error, I suspect this is a Power Apps environment issue.

Can you check that all users who have read access to the app also have read access to the 'Process' entity in the Power Platform admin center? See here - https://powerusers.microsoft.com/t5/Using-Connectors/connection-not-configured-for-this-service/td-p/891993.

Please can you raise a separate issue for the template screen lack of image in Teams.

Thanks

**Comment by mabaugh83** [comment]
this is now fixed
Per these instructions - except you cant modify the Basic User so you have to copy and then add the process to Org and then save and assign to the user 

Navigate to Power Apps Admin Center
Selected the Environment you are working. 
Click on Settings on top bar.  
Go to User + Permissions >> Security Roles  
Under the Security Roles, find the Basic User role , click on  ellipses (...) >> Edit
Under Customization tab >>  Select Process >> assign Read access to the Organization
