### ISSUE TITLE
Description field is cleared by the app

### ISSUE THREAD

**Issue by swallace74** [pnp/provision-assist-m365#100]
### Description

EDIT - This is in version 2.0.1. I've checked version 1.1.3 and the issue was not there.

After deploying the solution, I was testing with a standard user account and approvals flow worked however no Teams\Group object got created (when selecting the requirement option that would create a Microsoft Teams Team). Investigating the logic app, the run history showed a Bad Request with the Provision Group step in the ProcessProvisionRequest Logic app. The error was

code": "Request_BadRequest",
    "message": "Invalid value specified for property 'description' of resource 'Group'.",
    "details": [
      {
        "code": "InvalidLength",
        "message": "The description should be between 1 and 1024 characters.",
        "target": "description"

On checking the SharePoint Provisioning Requests list, the Description field was indeed empty for all the tests we had performed. On running through the app again (as a standard user), it was clear that whatever text is entered in the Description field in the Information screen is not saved and is missing when you get to the Review and Submit screen. After successful approval, this causes the logic app to fail.

### Steps to reproduce

1. Open the Provision Assist app and choose "Chat based instant collaboration within a Team" from the Requirements screen
2. Fill in all details in subsequent screens including the Description field
![DescriptionFieldInApp](https://github.com/user-attachments/assets/2375b065-f174-4aec-a260-3c9e0234886a)
4. On the Review and Submit screen, the Description field is showing as blank
![DescriptionBlankInReviewScreen](https://github.com/user-attachments/assets/a7bbf7f1-169f-4c42-8c45-318ced03d6c4)
6. If you proceed and click Submit and approve the request, no Group is created
7. The Description field in the Provisioning Requests list is blank for that request

### Expected results

The Description field should contain whatever text was entered by the user

### Actual Results

Description field is blank

### Solution component

Power App

### Operating system (environment)

Windows

**Comment by PrinsGeryha** [comment]
Can confirm the same issue here.

**Comment by alexc-MSFT** [comment]
@swallace74 @PrinsGeryha thanks, I can confirm I’ve found the bug and I will release a fix shortly in the form of an updated power apps solution. Thanks

**Comment by PrinsGeryha** [comment]
Yup, works like a charm now.

**Comment by alexc-MSFT** [comment]
@PrinsGeryha great, closing issue.
