### ISSUE TITLE
"Network error when using Patch function: The requested operation is invalid." in the Requirements screen of Power App (V2)

### ISSUE THREAD

**Issue by reikor0x** [pnp/provision-assist-m365#112]
### Description

Clicking Next in the Requirements screen of the Power Apps, I got this error "Network error when using Patch function: The requested operation is invalid."

Seems to be not related to permissions. I'm using the V2 app.

### Steps to reproduce

1. Load the app as user (Global Admin used)
2. Fill the initial Requirements screen with details, (Requirements, Owners)
3. Click Next for the next screen
4. Got the Error

### Expected results

Proceed to Reccomandation screen

### Actual Results

Got error when clicking Next

### Solution component

Power App

### Operating system (environment)

Windows

**Comment by reikor0x** [comment]
![image](https://github.com/user-attachments/assets/bd0be666-29ea-4563-b7fe-1440e6e1635c)

**Comment by reikor0x** [comment]
![image](https://github.com/user-attachments/assets/9d8dd2d5-75de-47c5-9d59-1c7370c1824d)

**Comment by reikor0x** [comment]
{
  "time": 1729863154507,
  "category": "Runtime",
  "name": "Unhandled error",
  "logLevel": 4,
  "data": {
    "errors": [
      {
        "Kind": 8,
        "Message": "Network error when using Patch function: The requested operation is invalid.",
        "Source": "buttonNextSRS.OnSelect",
        "Observed": "buttonNextSRS.OnSelect",
        "Details": {
          "HttpStatusCode": 400,
          "HttpResponse": "{\r\n  \"status\": 400,\r\n  \"message\": \"The passed-in field \\\"RequirementIds\\\" could not be found\\r\\nclientRequestId: 8993b791-44de-41f9-8dc6-e5bfc8e7f6e6\\r\\nserviceRequestId: dc605da1-30da-6000-c86f-b099fb105ece\"\r\n}"
        }
      }
    ],
    "info": "Network error when using Patch function: The requested operation is invalid.",
    "context": {
      "entityName": "buttonNextSRS",
      "propertyName": "OnSelect"
    }
  }
},

**Comment by reikor0x** [comment]
SOLVED.

Don't know why, in the [Provisioning Requests] list there was a missing column.
Opened the [Provisioning Requests] list in Sharepoint.
Created a new single line column called "RequirementIds" and I was able to proceed to the next page.



I'm not closing the BUG awaiting for owner analysis, if something needs to be patched.

**Comment by PrinsGeryha** [comment]
@reikor0x Can confirm same issue here with fresh install. Column is missing from the deployment.

**Comment by PrinsGeryha** [comment]
@reikor0x Using release version aswell. ProvisionAssist_v2.0.2 to be specific 👍

**Comment by reikor0x** [comment]
@alexc-MSFT  just published a code fix in this fork https://github.com/reikor0x/provision-assist-m365 or provide the permissions for a push request.

**Comment by alexc-MSFT** [comment]
@reikor0x only just saw this and I've already published a fix here - sorry! You should be able to create a PR from your fork for future changes, let me know if it doesn't work.

**Comment by alexc-MSFT** [comment]
Closing issue as this is now fixed in both releases.
