### ISSUE TITLE
Resource group not found error when deploying resources using Bicep template without explicit subscription setting

### ISSUE THREAD

**Issue by SkyNet-90** [pnp/provision-assist-m365#114]
### Description

We’re encountering an issue where the resource group (RG) is created successfully using the deploy.ps1 script, but when the deployment begins using a Bicep template, it fails with a "ResourceGroupNotFound" error.

After troubleshooting, we discovered that the issue is related to the active subscription context. By explicitly setting the subscription using az account set --subscription "<subscription-name>", the Bicep deployment is able to find the resource group and proceed as expected. This workaround resolved the issue, but it would be helpful if the script or template deployment could either automatically detect the resource group in the correct subscription or if a warning was given when the active subscription does not match.

We attempted multiple troubleshooting steps prior to discovering this solution, including:

1. Hardcoding the resource group name directly in the Bicep template instead of using a parameters file.
2. Adding a Read-Host pause to allow more time for the resource group creation to complete.
3. Confirming that we can create the resource group programmatically via Azure CLI without issues.
4. Despite these steps, the deployment script continued to fail to locate the resource group until we explicitly set the subscription.

### Steps to reproduce

1. Run the deploy.ps1 script to create the resource group and initiate the Bicep template deployment without explicitly setting the subscription.
2. Observe the "ResourceGroupNotFound" error when the Bicep template attempts to deploy resources to the specified resource group.
3. Set the correct subscription using az account set --subscription "<subscription-name>" and rerun the deployment. The deployment succeeds.

### Expected results

The Bicep template should deploy resources to the resource group that was created by the deploy.ps1 script without requiring an explicit subscription set, or provide a warning when the active subscription does not contain the specified resource group.

### Actual Results

The script outputs a "ResourceGroupNotFound" error when attempting to deploy resources via the Bicep template, despite the resource group being confirmed as created in Azure. Setting the correct subscription with az account set resolves the issue.

### Solution component

Deployment Script

### Operating system (environment)

Windows

### Additional Info

1. The issue only occurs when deploying resources through the Bicep template; the resource group creation itself completes successfully.
2. The resource group is verifiable in Azure after running the deploy.ps1 script.
3. Using Read-Host to pause the script and allow extra time for resource group creation did not resolve the issue.
4. We can create the resource group successfully using Azure CLI independently, suggesting that the issue may relate specifically to the Bicep template integration.
5. Explicitly setting the subscription using az account set --subscription "<subscription-name>" before deployment resolves the issue, but this step should ideally be handled automatically or documented as a prerequisite.

**Comment by alexc-MSFT** [comment]
@SkyNet-90 thanks for raising this one and thanks for all the detail - this really helped when fixing the issue.

I've updated the deployment script as per the solution that worked for you, we are now setting the correct subscription using az account set after logging into the CLI, this should fix the issue.

I've updated both releases with the fix.

Thanks
