### ISSUE TITLE
install fails on az login

### ISSUE THREAD

**Issue by mabaugh83** [pnp/provision-assist-m365#2]
### Description

found that install kept failing when the azure cli tries to login - got several ssl errors
issue was with certs but adding to chain did not fix it. 

had to run following powershell

& "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -m pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org pip-system-certs

### Steps to reproduce

1 run either createazureadapp or deploy scripts
2.
3.

### Expected results

continues without error

### Actual Results

error

### Solution component

Power App

### Operating system (environment)

Windows

**Comment by adam1309** [comment]
Installing AZ CLI from script in the PS window before running the script did it
