### ISSUE TITLE
No HubSites found

### ISSUE THREAD

**Issue by szucslaszloit** [pnp/provision-assist-m365#46]
### Description

In part 7, the join hub site does not find the hubsite, it says No Hubsites found - please clink 'Next'.
All settings have been successfully done professionally according to the deployment guide.

### Steps to reproduce

Just deploy it you will see

### Expected results

Users can see our Intranet hub site and they can select it.

### Actual Results

No Hubsites found - please clink 'Next'

### Solution component

Power App

### Operating system (environment)

Windows

### Additional Info

Unfortunately the Provisioning Assistant could not find our Hubiste:

![no_hubistes_found](https://github.com/pnp/provision-assist-m365/assets/96683851/8f546771-0729-4128-b379-cbe5eb0c3354)

By the way the hub site  + the Hub sites's ID appears in the sharepoint list 

![hubsite_list](https://github.com/pnp/provision-assist-m365/assets/96683851/3ec12d88-af2b-4afa-b651-a41679821473)

**Comment by alexc-MSFT** [comment]
@szucslaszloit you need to set the value of the 'Enabled' column to **true** in order for the hub site to be displayed in the app.

I'll make sure this is clear in the documentation.

Thanks
