### ISSUE TITLE
Logic App ProcessGuests fails while splitting Users String

### ISSUE THREAD

**Issue by wapster182** [pnp/provision-assist-m365#50]
### Description

The action "Split Users string" fails with the following error:

InvalidTemplate. Unable to process template language expressions in action 'Split_Guest_Users_string' inputs at line '0' and column '0': 'The template language function 'split' expects its first parameter to be of type string. The provided value is of type 'Null'. Please see https://aka.ms/logicexpressions#split for usage details.'.

It seems like the value is empty.

### Steps to reproduce

1. Run Logic app "ProcessGuests" manually
2. Check Logic app run details

### Expected results

Logic app gets executed successfully.

### Actual Results

Logic app is running on error.

### Solution component

Power App

### Operating system (environment)

Windows

### Additional Info

![image](https://github.com/pnp/provision-assist-m365/assets/68082620/8338890e-98ac-4d9c-8676-1d85938a1725)

**Comment by alexc-MSFT** [comment]
@wapster182 this logic app is not designed to be ran manually, it is executed from the main provisioning one (ProcessProvisionRequest) and a string containing the guest users to processed is passed to it, hence the error when running it manually as the string is null.

Closing this issue, if you find a bug when it is called from the main logic app then please raise a new one.

Thanks
