### ISSUE TITLE
Use the modern Microsoft Graph to create a Community in Viva Engage instead of using the classic Yammer developer functionality

### ISSUE THREAD

**Issue by haroldvandekamp** [pnp/provision-assist-m365#52]
### Suggestion

To enhance the Provision Assist to stay up to date, I would like to request an enhancement of the creation a Viva Engage Community by switching to the Microsoft Graph API. Can this be implemented?

### Classic route of creating a community in Viva Engage currently implemented in the Provision Assistant solution
The provision-assist-m365 documentation describes in [Step 12 (Optional): Enable provisioning of Viva Engage Communities](https://github.com/pnp/provision-assist-m365/blob/main/Deployment-guide.md#step-12-optional-enable-provisioning-of-viva-engage-communities) the old way of creating a community in Viva Engage, e.g. by referencing the previous product name Yammer and using the classic developer functionality of requesting the creation of a Yammer App Token during deployment of the solution. A great enhancement will be the use of the modern way of creating a Viva Engage Community by interacting with the Microsoft Graph API. 

### Suggested modern route of creating a community in Viva Engage to be implemented in the Provision Assistant solution
As described in the Microsoft Learn Documentation for Microsoft Graph at [Use the Microsoft Graph API to work with Viva Engage (preview)](https://learn.microsoft.com/en-us/graph/api/resources/engagement-api-overview?view=graph-rest-beta) under the /beta version of the the Microsoft Graph functionality is available to create a Viva Engage Community. The implementation steps including the App Registration in Microsoft Azure is described and depicted in Tech Community Blog [Introducing the Community Creation API for Viva Engage on Microsoft Graph Beta](https://techcommunity.microsoft.com/t5/viva-engage-blog/introducing-the-community-creation-api-for-viva-engage-on/ba-p/4011966). The following picture shows a community in Viva Engage created via the Microsoft Graph API.

![Community in Viva Engage created via the Microsoft Graph API](https://github.com/pnp/provision-assist-m365/assets/11357196/a8b67362-872c-4ad3-a979-937c88a13814)

**Important:** The Viva Engage API in Microsoft Graph is only supported for Viva Engage networks in native mode. You can't use this API to manage legacy or external Viva Engage networks.

**Comment by alexc-MSFT** [comment]
@haroldvandekamp nice enhancement! Yes we should definitely do this.

I will add it to the roadmap 😀

**Comment by alexc-MSFT** [comment]
This has now been completed in the latest release. FYI @haroldvandekamp

**Comment by haroldvandekamp** [comment]
Thanks @alexc-MSFT . Great to see that creation of a Viva Engage Community is now handled via the Microsoft Graph API.
