### ISSUE TITLE
Preview thumbnails and videos not displayed

### ISSUE THREAD

**Issue by wapster182** [pnp/provision-assist-m365#54]
### Description

Within the Power App, the thumbnails and videos are not displayed: 
![image](https://github.com/pnp/provision-assist-m365/assets/68082620/a2668431-b22a-432a-89d1-232ef916501c)

### Steps to reproduce

1. Start the app
2. Fill out first page requirements
3. Check collaboration spaces

### Expected results

Preview thumbnails and videos are displayed

### Actual Results

Preview thumbnails and videos are not displayed

### Solution component

Power App

### Operating system (environment)

Windows

**Comment by alexc-MSFT** [comment]
@wapster182 did you edit the app and reconnected the data sources to the environment variables again? If you miss this step then this happens.

**Comment by wapster182** [comment]
Thank you, it works now! My mistake...

![image](https://github.com/pnp/provision-assist-m365/assets/68082620/02458405-4c61-457d-9818-c0a6d283a1f8)

Weird that it was only affecting the Images. Well, nevermind.
