### ISSUE TITLE
Video Icon not shown

### ISSUE THREAD

**Issue by wapster182** [pnp/provision-assist-m365#56]
### Description

When choosing the collaboration space type, it says at the bottom: "To learn more about the different types, click the video icon."
However, there is no video icon shown. Where should it be in the App?

![image](https://github.com/pnp/provision-assist-m365/assets/68082620/1c646453-2076-4ab6-9888-b15b04c959f9)

### Steps to reproduce

1. Launch Power App
2. Fill in information and progress to step 2 Recommendation Screen
3. Try to find the video icon

### Expected results

There should be a video icon displayed.

### Actual Results

There is no video icon displayed.

### Solution component

Power App

### Operating system (environment)

Windows

**Comment by alexc-MSFT** [comment]
@wapster182 the video icon displays IF you have a URL to a video set in the 'Provisioning Types' list.

Hope this makes sense.

**Comment by wapster182** [comment]
Alright I see, are there any official links provided by Microsoft that we can use?

**Comment by alexc-MSFT** [comment]
@wapster182 I would recommend looking on docs.microsoft.com or the Microsoft channels on YouTube.
