### ISSUE TITLE
Option to skip Choose Template Screen

### ISSUE THREAD

**Issue by wapster182** [pnp/provision-assist-m365#60]
### Suggestion

We would love a quick option within the List "Provisioning Request Setting" with the option to disable the Choose Template screen, so that no template will be used.

**Comment by alexc-MSFT** [comment]
@wapster182 This is currently a work in progress and will be ready shortly.

**Comment by alexc-MSFT** [comment]
@wapster182 ok, this is now done, see the latest release of the Power App. 

You will need to add the following setting to the settings list:

![image](https://github.com/pnp/provision-assist-m365/assets/12395485/d8584064-a903-4887-9f4d-98e0b7efac08)

**Comment by alexc-MSFT** [comment]
@wapster182 please confirm when tested and I can close this

**Comment by wapster182** [comment]
This works great, the template screen is not showing up anymore when set to true. Thanks! Can be closed.

**Comment by alexc-MSFT** [comment]
@wapster182 perfect thanks
