### ISSUE TITLE
Option for auto-approval of requests

### ISSUE THREAD

**Issue by wapster182** [pnp/provision-assist-m365#61]
### Suggestion

We would like to have the option to auto approve all requests.
Maybe to make it work faster without the need to implement it into some setting, just give some info how to edit the Flow to auto approve it, so skipping the steps of Approvals (or add some actions in the Flow to set the SharePoint list items Status to approved automatically).

**Comment by alexc-MSFT** [comment]
@wapster182 I've implemented this via a new setting in the settings list and it will be released with the other new functionality that we are discussing.

**Comment by wapster182** [comment]
I tested this, unfortunately did not work yet.

![image](https://github.com/pnp/provision-assist-m365/assets/68082620/525d7411-76bc-4c3d-aae1-0eae1bd19bc0)

{
  "error": {
    "code": "BadRequest",
    "message": "Navigation binding uri for the property 'template@odata.bind' is not valid., Unable to extract object from request.",
    "innerError": {
      "date": "2024-02-09T15:41:49",
      "request-id": "f9f8e717-7843-49a5-a6c1-af5d8d279607",
      "client-request-id": "f9f8e717-7843-49a5-a6c1-af5d8d279607"
    }
  }
}


Do I need to re-run the scripts to create the logic apps? Is there anything changed in them that need to be updated?

**Comment by wapster182** [comment]
Hey @alexc-MSFT, could you check on this?

**Comment by wapster182** [comment]
Hi @alexc-MSFT, I just tested it: I Re-deployed the entire enviroment using the PS scripts, unfortunately the same error.
It seems the error has nothing to do with the auto-approval.
I set the value to false and the manuall approval was triggered. This has worked fine, until the Logic App tries to create the space. 

**Maybe there is something wrong because of the new skip template / default data classification setting?**

**Comment by wapster182** [comment]
I did some further testing. When I use a team site as space type, the logic app flow works and creates the space.

I think it has to be a **problem with the Teams creation** and the new skip template / default data classification.

Can you look into this?

**Comment by alexc-MSFT** [comment]
@wapster182 so yes as you say that error is not related to auto approval. Can you check the request in the Provisioning Requests list and look at the values of the 'Teams Template' and 'Teams Template Title' columns? I assume this request is using a custom template which perhaps can't be found. Let me know what those columns are populated with please. Thanks

**Comment by alexc-MSFT** [comment]
@wapster182 I've found the issue, the new setting for hiding the site template screen didn't take into account setting a default teams template (it should be set to 'Standard' for a provisioning request unless a template is specified). I've fixed the app, I just need to repackage it. You will only need to import the updated solution as opposed to any backend components.

**Comment by alexc-MSFT** [comment]
@wapster182 though it is worth noting I am about to push some general bug fixes too

**Comment by alexc-MSFT** [comment]
@wapster182 all done, the latest release contains the above fix and some other bug fixes (azure components)

**Comment by wapster182** [comment]
I wanted to test it, but it seems another BUG was introduced....
When trying to create a new request, I cannot go past the Recommendation screen in Step 2:

![image](https://github.com/pnp/provision-assist-m365/assets/68082620/e751cbc4-b829-412c-852b-8f84e6f32a21)

When hitting the Next button nothing happens.

Can you please check this soon, thank you

**Comment by alexc-MSFT** [comment]
@wapster182 so I've had this earlier during a deployment and it was due to the new columns not being created in the Provisioning Types list, we then had to refresh the list data source in the app and then republish.

Make sure the columns are created exactly as per this issue - https://github.com/pnp/provision-assist-m365/issues/59. Specifically the ones in the Provisioning Types list. Make sure the name is exactly the same too.

**Comment by wapster182** [comment]
Thanks, due to the re-import and re-executing of the scripts the SharePoint lists got somehow not overwritten but appended, so I had a mess in the columns: 
![image](https://github.com/pnp/provision-assist-m365/assets/68082620/3e58f6f8-d3d9-4be4-8c3d-49fef4417dd2)


Great advice, thanks. The auto-approval is working now!
