### ISSUE TITLE
Do you possible know whats the issue here? Best Regards Tahir

### ISSUE THREAD

**Issue by Tarrelito** [pnp/provision-assist-m365#7]
![image](https://github.com/pnp/provision-assist-m365/assets/144177246/3db64675-3d54-42b8-b99c-583517522e0f)

**Comment by Tarrelito** [comment]
We receive "Network error when using Patch function: You don't have permissions to edit this row." when i click on "next" inside the Teams.

**Comment by Tarrelito** [comment]
Nvm it was wrong permissions inside the SP site.

**Comment by alexc-MSFT** [comment]
@Tarrelito glad you got it resolved
