### ISSUE TITLE
Issue to set New and existing guests on SP site. 

### ISSUE THREAD

**Issue by Tarre86** [pnp/provision-assist-m365#75]
### Description

Hi! We have also issue to set New and existing guests on newly created SP site. We have set in the Provisioning Request Settings but still its not working. 
![image](https://github.com/pnp/provision-assist-m365/assets/26358608/9f399b40-95ff-4145-97cb-f2c8ee376cc5)

### Steps to reproduce

1.-
2.
3.

### Expected results

-

### Actual Results

-

### Solution component

Power App

### Operating system (environment)

Windows

**Comment by alexc-MSFT** [comment]
@Tarre86 I'm closing this issue as it relates to #74, it is the same bug
