### ISSUE TITLE
Support Sensitivity labels for Team Sites

### ISSUE THREAD

**Issue by Tarrelito** [pnp/provision-assist-m365#8]
Hi! 

I have just one question regarding the sensitivity labels when we choose “Team site”, we can not see the option “sensitivity label” in the request form? 

They are working good with Teams team and o365 groups in the form. 

Best Regards

**Comment by alexc-MSFT** [comment]
@Tarrelito we don't currently support setting sensitivity labels on SPO sites because of the lack of an API to do this. 

We store a service account in key vault but we don't actually use it in the Automation account.

We will look at adding this functionality in the future.

Thanks

**Comment by Tarrelito** [comment]
Okay thanks for the clarification.

**Comment by alexc-MSFT** [comment]
@Tarrelito adding to our roadmap in case we can find a better way to do this in the future.

**Comment by alexc-MSFT** [comment]
@Tarrelito we've just released V1.1.0 which now supports the application of sensitivity labels for SharePoint sites. I'm going to close this issue now and mark as done on the roadmap.

Please do check out the new release.

Thanks!
