### ISSUE TITLE
Defaulting to EN-US language not working - empty labels and texts

### ISSUE THREAD

**Issue by wapster182** [pnp/provision-assist-m365#85]
### Description

When your browser language is not in the translation libary (e.g. polish), it should default to en-US but this is not working.
You only see empty labels and no texts:

![image](https://github.com/user-attachments/assets/f1cbcc95-1760-4f90-acb8-ffa1f05948f8)

### Steps to reproduce

1. Set your browser language to something not included in the translation libary
2. Open the app
3. See missing labels and texts

### Expected results

When detected browser language is not included in translation libary, it should fallback to default en-US.

### Actual Results

It displays no text and empty labels:

![image](https://github.com/user-attachments/assets/f1cbcc95-1760-4f90-acb8-ffa1f05948f8)

### Solution component

Power App

### Operating system (environment)

Windows

**Comment by alexc-MSFT** [comment]
@wapster182 thanks for spotting this, I'll take a look.

Also, we would love to get more translations into the solution so if you'd like to help and add Polish in there we would be most grateful.

Thanks

**Comment by alexc-MSFT** [comment]
@wapster182 I've now fixed this - thanks for your patience and good spot too.

The latest 1.1.3 release - https://github.com/pnp/provision-assist-m365/releases/tag/v1.1.3 contains the fix.

Or if you wish to use the V2 UI, the latest V2 release (2.0.1) also contains the fix.

Closing this issue now. Thanks

**Comment by wapster182** [comment]
Great, thanks!
Do you have anything documented regarding to the V2 UI? The screenshots from the guide are still the V1.x UI, right?

**Comment by ghost** [comment]
Hi there, unfortunately i have same issue with version 2.0.8:

![Image](https://github.com/user-attachments/assets/bc319f4d-aa0c-4eb0-810e-f3bf43f44dad)

**Comment by ghost** [comment]
> Hi there, unfortunately i have same issue with version 2.0.8:
> 
> ![Image](https://github.com/user-attachments/assets/bc319f4d-aa0c-4eb0-810e-f3bf43f44dad)

My browser had few languages:
-English
-Polish
-English (US)
-English (UK)
Once i've changed default language for English (US) the correct labels appeared.

It seems that default language (EN-US) doesn't works.
