### ISSUE TITLE
A few niggles with CreateEntraIDAppSecret function

### ISSUE THREAD

**Issue by lhaynes1970** [pnp/provision-assist-m365#96]
### Description

1. CreateEntraIDAppSecret is created but not called as a function later in the script but CreateAzureADAppSecret is called. However, this is not a defined function for that. Have renamed the call for CreateAzureADAppSecret to CreateEntraIDAppSecret.
2. function CreateEntraIDAppSecret - Line 699 - $app = GetAzureADApp $parameters.appName.Value........GetAzureADApp doesnt exist as a cmdlet.

### Steps to reproduce

1.Run deploy.ps1
2.
3.

### Expected results

Creat entra app secret

### Actual Results

The term 'CreateAzureADAppSecret' is not recognized as a name of a cmdlet, function, script file, or executable program.

GetAzureADApp: The term 'GetAzureADApp' is not recognized as a name of a cmdlet, function, script file, or executable program.

### Solution component

Deployment Script

### Operating system (environment)

Windows

### Additional Info
v2.0.0a

**Comment by alexc-MSFT** [comment]
@lhaynes1970 good spot, looks like I forgot to update these references when I changed the functions to represent the change from AD to Entra. I've just fixed this, thanks.

**Comment by lhaynes1970** [comment]
Many thanks @alexc-MSFT much appreciated

**Comment by reikor0x** [comment]
Release is not up-to-date
