### ISSUE TITLE
Link to Solution Overview in documentation

### ISSUE THREAD

**Issue by swallace74** [pnp/provision-assist-m365#99]
### Documentation inaccuracy

The last paragraph in section 8 (pasted below) has a link to "Solution Overview" however the link doesn't resolve and I couldn't find solution overview in the project. Not sure if there needs to be an internal link here, maybe just an external link to the MS article - https://learn.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/set-adminpowerappapistobypassconsent?view=pa-ps-latest

### Additional Info

Note: Every user accessing the app for the first time will be prompted to consent to accessing the data sources. The user should click on 'Allow' to proceed. This can be bypassed by using the Power Apps admin PowerShell module. See the [Solution Overview](https://github.com/pnp/provision-assist-m365/blob/main/Solution-Overview) for more details. It is recommended to disable the consent popup using PowerShell before production deployment.

**Comment by alexc-MSFT** [comment]
@swallace74 thanks for raising this, I've fixed and updated this documentation now.
